#!/usr/bin/env node

// Asset export script for marketing materials

const fs = require('fs/promises');
const path = require('path');

/**
 * Export all marketing assets to various formats and sizes
 */
async function exportAssets() {
  console.log('🎨 Exporting ManagerX marketing assets...');
  
  try {
    await createAssetIndex();
    await generateSteamAssets();
    await generateGOGAssets();
    await generateSocialMediaAssets();
    await generatePressKitAssets();
    
    console.log('✅ All marketing assets exported successfully!');
    console.log('📂 Check marketing/exports/ for all generated files');
    
  } catch (error) {
    console.error('❌ Asset export failed:', error);
    process.exit(1);
  }
}

/**
 * Create asset index for easy reference
 */
async function createAssetIndex() {
  const assetsDir = path.join(__dirname, '../exports');
  await fs.mkdir(assetsDir, { recursive: true });
  
  const index = `# ManagerX Marketing Assets

Generated on: ${new Date().toISOString()}

## Icons
- icon-16.svg (16x16) - Favicon, small UI elements
- icon-32.svg (32x32) - Taskbar, notifications
- icon-64.svg (64x64) - Desktop shortcuts, medium UI

## Store Assets

### Steam
- steam-capsule-main.svg (616x353) - Main store capsule
- steam-header.svg (460x215) - Header capsule
- steam-library-hero.svg (1920x620) - Library hero image
- steam-small-capsule.svg (231x87) - Small capsule
- steam-icon.svg (184x184) - Steam icon

### GOG
- gog-logo.svg (200x200) - GOG store logo
- gog-banner.svg (1200x400) - GOG banner
- gog-thumbnail.svg (300x300) - Thumbnail

## Social Media
- og-image.png (1200x630) - Open Graph image
- twitter-card.png (1200x675) - Twitter card
- facebook-cover.png (1640x859) - Facebook cover
- discord-logo.png (512x512) - Discord server icon

## Press Kit
- logo-horizontal.svg - Horizontal logo layout
- logo-vertical.svg - Vertical logo layout
- logo-monochrome.svg - Single color version
- logo-white.svg - White version for dark backgrounds

## Usage Guidelines

### Colors
- Primary Green: #00ff00
- Dark Green: #009900
- Background: #000000
- Grid Accent: rgba(0,255,0,0.3)

### Typography
- Primary: Courier New, monospace
- Fallback: Monaco, 'Lucida Console', monospace

### Style Guidelines
- Retro/CRT aesthetic inspired by early 2000s
- Minimalist low-poly approach
- Green monochrome palette
- ASCII art elements where appropriate
- Nostalgic but modern feel

### Usage Rights
- Free to use for ManagerX promotion
- Credit ManagerX team when possible
- Do not modify core logo elements
- Maintain aspect ratios
- Use provided color schemes

---

*Assets generated by ManagerX marketing system*`;

  await fs.writeFile(path.join(assetsDir, 'README.md'), index);
}

/**
 * Generate Steam-specific assets
 */
async function generateSteamAssets() {
  console.log('🎮 Generating Steam assets...');
  
  // Create Steam asset variations
  const steamAssets = {
    'steam-small-capsule.svg': generateSteamSmallCapsule(),
    'steam-icon.svg': generateSteamIcon(),
  };
  
  const steamDir = path.join(__dirname, '../exports/steam');
  await fs.mkdir(steamDir, { recursive: true });
  
  for (const [filename, content] of Object.entries(steamAssets)) {
    await fs.writeFile(path.join(steamDir, filename), content);
  }
  
  // Copy existing Steam assets
  const existingAssets = [
    'steam-capsule-main.svg',
    'steam-header.svg',
    'steam-library-hero.svg',
  ];
  
  for (const asset of existingAssets) {
    const sourcePath = path.join(__dirname, '../store-assets', asset);
    const destPath = path.join(steamDir, asset);
    
    try {
      await fs.copyFile(sourcePath, destPath);
    } catch (error) {
      console.warn(`Could not copy ${asset}:`, error.message);
    }
  }
}

/**
 * Generate GOG-specific assets
 */
async function generateGOGAssets() {
  console.log('🎯 Generating GOG assets...');
  
  const gogAssets = {
    'gog-banner.svg': generateGOGBanner(),
    'gog-thumbnail.svg': generateGOGThumbnail(),
  };
  
  const gogDir = path.join(__dirname, '../exports/gog');
  await fs.mkdir(gogDir, { recursive: true });
  
  for (const [filename, content] of Object.entries(gogAssets)) {
    await fs.writeFile(path.join(gogDir, filename), content);
  }
  
  // Copy existing GOG logo
  const sourcePath = path.join(__dirname, '../store-assets/gog-logo.svg');
  const destPath = path.join(gogDir, 'gog-logo.svg');
  
  try {
    await fs.copyFile(sourcePath, destPath);
  } catch (error) {
    console.warn('Could not copy GOG logo:', error.message);
  }
}

/**
 * Generate social media assets
 */
async function generateSocialMediaAssets() {
  console.log('📱 Generating social media assets...');
  
  const socialAssets = {
    'og-image.svg': generateOGImage(),
    'twitter-card.svg': generateTwitterCard(),
    'discord-logo.svg': generateDiscordLogo(),
  };
  
  const socialDir = path.join(__dirname, '../exports/social');
  await fs.mkdir(socialDir, { recursive: true });
  
  for (const [filename, content] of Object.entries(socialAssets)) {
    await fs.writeFile(path.join(socialDir, filename), content);
  }
}

/**
 * Generate press kit assets
 */
async function generatePressKitAssets() {
  console.log('📰 Generating press kit assets...');
  
  const pressAssets = {
    'logo-horizontal.svg': generateHorizontalLogo(),
    'logo-vertical.svg': generateVerticalLogo(),
    'logo-monochrome.svg': generateMonochromeLogo(),
    'logo-white.svg': generateWhiteLogo(),
  };
  
  const pressDir = path.join(__dirname, '../exports/press-kit');
  await fs.mkdir(pressDir, { recursive: true });
  
  for (const [filename, content] of Object.entries(pressAssets)) {
    await fs.writeFile(path.join(pressDir, filename), content);
  }
}

// Asset generation functions
function generateSteamSmallCapsule() {
  return `<!-- Steam Small Capsule: 231x87px -->
<svg width="231" height="87" viewBox="0 0 231 87" xmlns="http://www.w3.org/2000/svg">
  <rect width="231" height="87" fill="#000000"/>
  <text x="115" y="35" text-anchor="middle" font-family="Courier New, monospace" font-size="24" font-weight="bold" fill="#00ff00">
    ManagerX
  </text>
  <text x="115" y="55" text-anchor="middle" font-family="Courier New, monospace" font-size="12" fill="#00ff00" opacity="0.8">
    Football Manager
  </text>
  <circle cx="115" cy="75" r="3" fill="#00ff00"/>
</svg>`;
}

function generateSteamIcon() {
  return `<!-- Steam Icon: 184x184px -->
<svg width="184" height="184" viewBox="0 0 184 184" xmlns="http://www.w3.org/2000/svg">
  <rect width="184" height="184" fill="#000000"/>
  <g transform="translate(92, 92)">
    <rect x="-30" y="-40" width="6" height="60" fill="#00ff00"/>
    <rect x="24" y="-40" width="6" height="60" fill="#00ff00"/>
    <polygon points="-24,-40 -10,-15 -15,-15 -24,-30" fill="#00ff00"/>
    <polygon points="24,-40 10,-15 15,-15 24,-30" fill="#00ff00"/>
    <polygon points="-10,-15 0,-25 10,-15 5,-10 0,-20 -5,-10" fill="#00ff00"/>
  </g>
  <circle cx="92" cy="160" r="6" fill="none" stroke="#00ff00" stroke-width="2"/>
</svg>`;
}

function generateGOGBanner() {
  return `<!-- GOG Banner: 1200x400px -->
<svg width="1200" height="400" viewBox="0 0 1200 400" xmlns="http://www.w3.org/2000/svg">
  <rect width="1200" height="400" fill="#000000"/>
  <text x="600" y="200" text-anchor="middle" font-family="Courier New, monospace" font-size="80" font-weight="bold" fill="#00ff00">
    ManagerX
  </text>
  <text x="600" y="240" text-anchor="middle" font-family="Courier New, monospace" font-size="24" fill="#00ff00" opacity="0.8">
    The Ultimate Football Manager • DRM-Free
  </text>
</svg>`;
}

function generateGOGThumbnail() {
  return `<!-- GOG Thumbnail: 300x300px -->
<svg width="300" height="300" viewBox="0 0 300 300" xmlns="http://www.w3.org/2000/svg">
  <rect width="300" height="300" fill="#000000"/>
  <circle cx="150" cy="150" r="140" fill="none" stroke="#00ff00" stroke-width="2" opacity="0.3"/>
  <text x="150" y="150" text-anchor="middle" font-family="Courier New, monospace" font-size="36" font-weight="bold" fill="#00ff00">
    ManagerX
  </text>
  <text x="150" y="180" text-anchor="middle" font-family="Courier New, monospace" font-size="16" fill="#00ff00" opacity="0.8">
    DRM-FREE
  </text>
</svg>`;
}

function generateOGImage() {
  return `<!-- Open Graph: 1200x630px -->
<svg width="1200" height="630" viewBox="0 0 1200 630" xmlns="http://www.w3.org/2000/svg">
  <rect width="1200" height="630" fill="#000000"/>
  <text x="600" y="250" text-anchor="middle" font-family="Courier New, monospace" font-size="100" font-weight="bold" fill="#00ff00">
    ManagerX
  </text>
  <text x="600" y="320" text-anchor="middle" font-family="Courier New, monospace" font-size="32" fill="#00ff00" opacity="0.8">
    Championship Manager 01/02 + Modern AI
  </text>
  <text x="600" y="380" text-anchor="middle" font-family="Courier New, monospace" font-size="24" fill="#00ff00" opacity="0.7">
    Deep Tactics • AI Assistant • 6 Leagues • 200+ Clubs
  </text>
</svg>`;
}

function generateTwitterCard() {
  return `<!-- Twitter Card: 1200x675px -->
<svg width="1200" height="675" viewBox="0 0 1200 675" xmlns="http://www.w3.org/2000/svg">
  <rect width="1200" height="675" fill="#000000"/>
  <text x="600" y="280" text-anchor="middle" font-family="Courier New, monospace" font-size="90" font-weight="bold" fill="#00ff00">
    ManagerX
  </text>
  <text x="600" y="340" text-anchor="middle" font-family="Courier New, monospace" font-size="28" fill="#00ff00" opacity="0.8">
    The Ultimate Football Manager
  </text>
  <text x="600" y="420" text-anchor="middle" font-family="Courier New, monospace" font-size="20" fill="#00ff00" opacity="0.7">
    🎯 Deep Tactics • 🤖 AI Assistant • ⚡ Offline-First
  </text>
</svg>`;
}

function generateDiscordLogo() {
  return `<!-- Discord Logo: 512x512px -->
<svg width="512" height="512" viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg">
  <circle cx="256" cy="256" r="256" fill="#000000"/>
  <circle cx="256" cy="256" r="240" fill="none" stroke="#00ff00" stroke-width="2" opacity="0.3"/>
  <text x="256" y="220" text-anchor="middle" font-family="Courier New, monospace" font-size="48" font-weight="bold" fill="#00ff00">
    ManagerX
  </text>
  <text x="256" y="260" text-anchor="middle" font-family="Courier New, monospace" font-size="20" fill="#00ff00" opacity="0.8">
    Community
  </text>
  <circle cx="256" cy="320" r="8" fill="#00ff00"/>
</svg>`;
}

function generateHorizontalLogo() {
  return `<!-- Horizontal Logo: 400x120px -->
<svg width="400" height="120" viewBox="0 0 400 120" xmlns="http://www.w3.org/2000/svg">
  <g transform="translate(60, 60)">
    <!-- M logo -->
    <rect x="-25" y="-35" width="5" height="50" fill="#00ff00"/>
    <rect x="20" y="-35" width="5" height="50" fill="#00ff00"/>
    <polygon points="-20,-35 -8,-15 -12,-15 -20,-25" fill="#00ff00"/>
    <polygon points="20,-35 8,-15 12,-15 20,-25" fill="#00ff00"/>
    <polygon points="-8,-15 0,-25 8,-15 5,-10 0,-20 -5,-10" fill="#00ff00"/>
  </g>
  
  <text x="150" y="70" font-family="Courier New, monospace" font-size="48" font-weight="bold" fill="#00ff00">
    ManagerX
  </text>
</svg>`;
}

function generateVerticalLogo() {
  return `<!-- Vertical Logo: 200x300px -->
<svg width="200" height="300" viewBox="0 0 200 300" xmlns="http://www.w3.org/2000/svg">
  <g transform="translate(100, 100)">
    <!-- M logo -->
    <rect x="-30" y="-40" width="6" height="60" fill="#00ff00"/>
    <rect x="24" y="-40" width="6" height="60" fill="#00ff00"/>
    <polygon points="-24,-40 -10,-15 -15,-15 -24,-30" fill="#00ff00"/>
    <polygon points="24,-40 10,-15 15,-15 24,-30" fill="#00ff00"/>
    <polygon points="-10,-15 0,-25 10,-15 5,-10 0,-20 -5,-10" fill="#00ff00"/>
  </g>
  
  <text x="100" y="200" text-anchor="middle" font-family="Courier New, monospace" font-size="32" font-weight="bold" fill="#00ff00">
    ManagerX
  </text>
  
  <text x="100" y="230" text-anchor="middle" font-family="Courier New, monospace" font-size="14" fill="#00ff00" opacity="0.8">
    Football Manager
  </text>
</svg>`;
}

function generateMonochromeLogo() {
  return `<!-- Monochrome Logo: 300x150px -->
<svg width="300" height="150" viewBox="0 0 300 150" xmlns="http://www.w3.org/2000/svg">
  <g transform="translate(75, 75)">
    <rect x="-25" y="-35" width="5" height="50" fill="#333333"/>
    <rect x="20" y="-35" width="5" height="50" fill="#333333"/>
    <polygon points="-20,-35 -8,-15 -12,-15 -20,-25" fill="#333333"/>
    <polygon points="20,-35 8,-15 12,-15 20,-25" fill="#333333"/>
    <polygon points="-8,-15 0,-25 8,-15 5,-10 0,-20 -5,-10" fill="#333333"/>
  </g>
  
  <text x="150" y="85" text-anchor="middle" font-family="Courier New, monospace" font-size="36" font-weight="bold" fill="#333333">
    ManagerX
  </text>
</svg>`;
}

function generateWhiteLogo() {
  return `<!-- White Logo: 300x150px -->
<svg width="300" height="150" viewBox="0 0 300 150" xmlns="http://www.w3.org/2000/svg">
  <g transform="translate(75, 75)">
    <rect x="-25" y="-35" width="5" height="50" fill="#ffffff"/>
    <rect x="20" y="-35" width="5" height="50" fill="#ffffff"/>
    <polygon points="-20,-35 -8,-15 -12,-15 -20,-25" fill="#ffffff"/>
    <polygon points="20,-35 8,-15 12,-15 20,-25" fill="#ffffff"/>
    <polygon points="-8,-15 0,-25 8,-15 5,-10 0,-20 -5,-10" fill="#ffffff"/>
  </g>
  
  <text x="150" y="85" text-anchor="middle" font-family="Courier New, monospace" font-size="36" font-weight="bold" fill="#ffffff">
    ManagerX
  </text>
</svg>`;
}

function generateSocialMediaAssets() {
  console.log('📱 Generating social media assets...');
  // Social media assets would be generated here
  // For now, we'll create the SVG versions
}

function generatePressKitAssets() {
  console.log('📰 Generating press kit...');
  // Press kit assets generated above
}

// Run if called directly
if (require.main === module) {
  exportAssets().catch(console.error);
}

module.exports = { exportAssets };
